---
user:
  name: jamagee

base_packages:
  - 7zip
  - aria2
  - cmder
  - coreutils
  - curl
  - git
  - jq
  - less
  - nano
  - psutils
  - ripgrep
  - sed
  - unzip
  - wget
  - win32-openssh
  - zip

vscode_extensions:
  - DavidAnson.vscode-markdownlint
  - Equinusocio.vsc-material-theme
  - Equinusocio.vsc-material-theme-icons
  - Orta.vscode-jest
  - PeterJausovec.vscode-docker
  - eamodio.gitlens
  - eg2.tslint
  - esbenp.prettier-vscode
  - formulahendry.auto-rename-tag
  - foxundermoon.shell-format
  - gio00.fish
  - James-Yu.latex-workshop
  - jithurjacob.nbpreviewer
  - dotjoshjohnson.xml
  - lunaryorn.fish-ide
  - ms-azuretools.vscode-azurefunctions
  - ms-python.python
  - ms-vscode.azure-account
  - ms-vscode.csharp
  - ms-vscode.mono-debug
  - ms-vscode.PowerShell
  - pnp.polacode
  - redhat.vscode-yaml
  - streetsidesoftware.code-spell-checker
  - vscoss.vscode-ansible