---
- name: Install JDKs
  win_scoop:
    name:
      - adopt8-hotspot
      - adopt11-hotspot
      - adopt12-hotspot

- name: Set default JDK
  win_shell: 'scoop reset adopt8-hotspot'

- name: Install maven
  win_scoop:
    name: maven

- name: Install gradle
  win_scoop:
    name: gradle
# - name: Install jetty
#   win_scoop:
#     name: jetty
