---
- include: packages.yml

- name: Install all windows updates
  win_updates:
    category_names:
      - Application
      - Connectors
      - CriticalUpdates
      - DefinitionUpdates
      - DeveloperKits
      - FeaturePacks
      - Guidance
      - SecurityUpdates
      - ServicePacks
      - Tools
      - UpdateRollups
      - Updates

- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest
